### ISSUE TITLE
Support for Translations possible?

### ISSUE THREAD

**Issue by deckerweb** [afragen/local-development#1]
Hi Andy,
I really love this plugin, it is really helpful for me.

Lately one thing that bothers me, is, WordPress always overriding my translations when I test new versions of my plugins (that are already on .org repo).

The plugin is already set as local dev in your plugin and works like a charm. But translations are not automatically blocked (seems totally a WP thing).

Would it be possible at all to block translation updates - I guess WP can only block translations at all but not on a per plugin level?

If there might be still a chance I would love it. This would save me lots of time and nerves... :-)
I would think of an extra settings page - or even a combined one: I check a plugin as local and beside it I can optionally check translations for this plugin.

In other news, to show my way of support and saying thank you, I already support your plugin in my Toolbar Extras plugin :-)

**Comment by afragen** [comment]
It sounds like it should be a combined thing depending upon the plugin/theme. I'll have to look into it. It should be possible.

**Comment by afragen** [comment]
See if the above works. It on the develop branch.

I think this should work on a per plugin/theme basis.

**Comment by deckerweb** [comment]
Oh, thanks so much! Just tested on 2 local installs and it seems to work perfectly. I will watch the next few days. But thanks again 👍

**Comment by afragen** [comment]
Ping me again when you feel it’s solid and I’ll merge and release.

**Comment by deckerweb** [comment]
Absolutely, yes

**Comment by afragen** [comment]
Hey David! How has the `develop` branch been working for you?

**Comment by deckerweb** [comment]
It's all working fine, thanks!
