### ISSUE TITLE
Version 2.5.0 on wp.org?

### ISSUE THREAD

**Issue by Raruto** [afragen/local-development#11]
I'm trying version 2.5.0 uploaded on wp.org, but **it doesn't show the icons** within the plugins.php page in any way. Downloading it from here, on GitHub, instead, it works out of the box ...

_Are you sure you have uploaded the right version on wp.org?_

**Comment by afragen** [comment]
It seems you need to save settings at least once. Not sure why though. I’ll see about it.

**Comment by afragen** [comment]
v2.5.1 should fix this.
