### ISSUE TITLE
WSOD wp-config.php not writeable

### ISSUE THREAD

**Issue by mediaformat** [afragen/local-development#15]
WSOD after setting environment, perhaps a warning message before hand, or better yet checking its writability would be helpful.
 
`Caught Exception: \Fragen\Local_Development\Init::__construct() - wp-config.php is not writable.`

**Comment by afragen** [comment]
That's the check to see if wp-config.php is writable. What you see is the error/notification.

**Comment by mediaformat** [comment]
Right, I'm saying that the check or warning should happen before the user saves the option, since this message only appears once the site is completely unusable (I had to ssh into the server and rename the folder to disable the plugin!)

This happened in `production`!

**Comment by afragen** [comment]
Sorry. I'll take a look at how to make it less invasive.

**Comment by afragen** [comment]
`production`?, this plugin is really for local development.

**Comment by mediaformat** [comment]
Sorry I misread how this worked, and installed at the same time as a git plugin!
