### ISSUE TITLE
Automatically detect under development plugins

### ISSUE THREAD

**Issue by Raruto** [afragen/local-development#4]
In the coming months I would like to update (add / remove some features) [my plugin](https://github.com/Raruto/wp-devops) that I already use as development support.

Inside it has a functionality very similar to yours which allows me to automatically check if a plugin is actually under development for the current machine.

To avoid unnecessary work, could it be interesting to add this functionality to this plugin?

**Comment by afragen** [comment]
That would be great !

**Comment by afragen** [comment]
@Raruto let me  know what you think.
